Repository TakshakRamteke/dashcord, pull requests merged in 2022-05, with the labels that each got.

#13 Feat + Fix : TG incharge dashboard - Students feature
  lib/prisma.ts
  pages/api/auth/[...auth0].js
  pages/api/students/[id].ts
  pages/api/students/index.ts
  pages/index.tsx
  pages/students/[slug].tsx
  pages/students/index.tsx
  prisma/schema.prisma
Labels: Database, dashboard, Good first issue, TG Incharge, TG, HOD

#14 Feat + Fix
  pages/api/students/[id].ts
  pages/students/[slug].tsx
  prisma/schema.prisma
  prisma/seed.ts
Labels: Database, dashboard, enhancement, TG Incharge, TG, Students, HOD, Parents

#15 Fix
  package.json
  pages/_app.tsx
  pages/api/auth/[...nextauth].ts
  tsconfig.json
  yarn.lock
Labels: Database, dashboard, enhancement, TG Incharge, TG, Students, HOD, Parents

#16 feat : add login page
  pages/login.tsx
Labels: dashboard

#18 Feat + Fix
  .env.example
  components/Sidebar.tsx
  package.json
  pages/api/attendances.ts
  pages/api/auth/[...nextauth].ts
  pages/index.tsx
  pages/login.tsx
  prisma/schema.prisma
  prisma/seed.ts
  tsconfig.json
  yarn.lock
Labels: Database, dashboard, TG Incharge

#19 Feat + Fixes
  components/Layout.tsx
  components/Table/Table.tsx
  components/cards/Card.tsx
  lib/prisma.js
  lib/prisma.ts
  pages/api/attendances.ts
  pages/index.tsx
  prisma/schema.prisma
  tsconfig.json
Labels: Database, dashboard, TG Incharge

#20 Feat + Fix
  components/Layout/TgLayout.tsx
  components/Sidebar/TgSidebar.tsx
  lib/validateUser.ts
  pages/api/tg/auth/[...nextauth].ts
  pages/api/tg/index.ts
  pages/api/tg/students/index.ts
  pages/chat.tsx
  pages/incharge/index.tsx
  pages/index.tsx
  pages/notifications.tsx
  pages/students/index.tsx
  pages/tg/index.tsx
  pages/tg/login.tsx
  pages/tg/settings.tsx
  pages/tg/students/[slug].tsx
  pages/tg/students/index.tsx
  pages/tg/user.tsx
  pages/user.tsx
Labels: Database, dashboard, TG Incharge

#21 Feat : Added signup page for students
  package.json
  pages/api/signup.ts
  pages/details.tsx
  pages/login.tsx
  pages/signup.tsx
  pages/tg/index.tsx
  pages/tg/students/[slug].tsx
  pages/tg/students/index.tsx
  prisma/schema.prisma
  yarn.lock
Labels: dashboard, Students

#23 Feat : Dynamic sidebar
  components/Sidebar/TgSidebar.tsx
Labels: dashboard, TG Incharge, TG, Students, HOD, Parents

#28 Minor fixes
  lib/validateUser.ts
  pages/INCHARGE/index.tsx
  pages/INCHARGE/login.tsx
  pages/INCHARGE/students/[slug].tsx
  pages/INCHARGE/students/index.tsx
  pages/INCHARGE/user.tsx
  pages/STUDENT/index.tsx
  pages/STUDENT/user.tsx
  pages/TG/index.tsx
  pages/TG/login.tsx
  pages/TG/settings.tsx
  pages/TG/students/[slug].tsx
  pages/TG/students/index.tsx
  pages/TG/user.tsx
  pages/api/auth/[...nextauth].ts
Labels: Database, dashboard, Students

#29 Fix : Edited readme to contain structure of readme
  readme.md
Labels: documentation, enhancement

#30 Fix : minor fixes
  pages/INCHARGE/students/index.tsx
  pages/TG/students/index.tsx
Labels: enhancement

#31 Fix : Switched to a light theme for TG
  components/Layout/TgLayout.tsx
  components/Sidebar/TgSidebar.tsx
  components/Table/Table.tsx
  components/cards/Card.tsx
  pages/INCHARGE/index.tsx
  pages/INCHARGE/students/[slug].tsx
  pages/INCHARGE/user.tsx
  pages/STUDENT/user.tsx
  pages/TG/students/[slug].tsx
  pages/TG/students/index.tsx
  pages/TG/user.tsx
Labels: dashboard, TG

#32 Feat : Added performance chart for each student (static for now)
  components/Table/Table.tsx
  pages/TG/students/[slug].tsx
Labels: dashboard, TG Incharge, TG, Students, HOD, Parents

#33 Fix : Minor fixes
  pages/TG/students/[slug].tsx
  prisma/schema.prisma
Labels: Database, dashboard

#34 Fix + Feat
  .gitignore
  components/Layout/TgLayout.tsx
  components/Sidebar/TgSidebar.tsx
  cypress.json
  cypress/fixtures/example.json
  cypress/integration/Authentication.feature
  cypress/integration/Home.feature
  cypress/integration/common/index.js
  cypress/plugins/index.js
  cypress/support/commands.js
  cypress/support/index.js
  package.json
  pages/TG/index.tsx
  pages/TG/students/[slug].tsx
  pages/api/auth/[...nextauth].ts
  pages/index.tsx
  pages/login.tsx
  pages/signout.tsx
  prisma/seed.ts
  yarn.lock
Labels: Database, dashboard

#35 Feat + Fix
  cypress/integration/Home.feature
  docs/dashcord-sequenceDigram.drawio
  docs/dashcord-systemArchitecture.drawio
  docs/dashcord-useCaseDigram.drawio
  pages/index.tsx
Labels: enhancement

#38 minor features
  pages/TEACHER/index.tsx
  pages/TEACHER/login.tsx
  pages/api/teacher/auth/[...nextauth].ts
Labels: dashboard

#39 Fix : Added tech stack to readme
  readme.md
Labels: documentation

#41 minor Fix + Feat
  pages/TG/students/[slug].tsx
  pages/api/tg/auth/[...nextauth].ts
  prisma/seed.ts
Labels: Database, dashboard, TG Incharge, TG, Students, HOD

#42 Fix : Delete existing students on seed
  prisma/seed.ts
Labels: Database

#43 Minor Fix
  pages/TG/index.tsx
  pages/TG/students/[slug].tsx
  prisma/schema.prisma
Labels: Database, dashboard
