Repository TakshakRamteke/dashcord, pull requests merged in 2022-08, with the labels that each got.

#81 Minor feat + Fix
  .gitignore
  package.json
  pages/api/hello.ts
  pages/login.tsx
  pages/signout.tsx
  prisma/seed.ts
  tsconfig.json
  yarn.lock
Labels: Database, enhancement, Students

#82 Minor Feat + Fix
  .gitignore
  package.json
  pages/api/hello.ts
  pages/login.tsx
  pages/signout.tsx
  prisma/seed.ts
  tsconfig.json
  yarn.lock
Labels: Database, dashboard, Students

#83 psudo V1 launch test deployment build
  components/Forms/CurrentAcademicDetails.tsx
  components/Forms/FamilyDetail.tsx
  components/Forms/FriendsDetail.tsx
  components/Forms/MediaclDetailForm.tsx
  components/Forms/PastAcademicDetailForm.tsx
  components/Forms/PersonalDetail.tsx
  components/LoadingIcon.tsx
  components/Toast.tsx
  lib/passHash.ts
  lib/validateUser.ts
  lib/xlSchema.ts
  package.json
  pages/api/auth/[...nextauth].ts
  pages/api/signup.ts
  pages/details.tsx
  pages/index.tsx
  pages/login.tsx
  pages/signout.tsx
  prisma/seed.ts
  yarn.lock
Labels: Database, dashboard, enhancement, Students

#84 psuedo V1 Deployment build
  components/Forms/CurrentAcademicDetails.tsx
  components/Forms/FamilyDetail.tsx
  components/Forms/FriendsDetail.tsx
  components/Forms/MediaclDetailForm.tsx
  components/Forms/PastAcademicDetailForm.tsx
  components/Forms/PersonalDetail.tsx
  components/LoadingIcon.tsx
  components/Toast.tsx
  lib/passHash.ts
  lib/validateUser.ts
  lib/xlSchema.ts
  package.json
  pages/api/auth/[...nextauth].ts
  pages/api/signup.ts
  pages/details.tsx
  pages/index.tsx
  pages/login.tsx
  pages/signout.tsx
  prisma/seed.ts
  yarn.lock
Labels: Database, dashboard, enhancement, Students

#85 Dakhole
  components/Forms/PersonalDetail.tsx
  pages/api/signup.ts
  pages/details.tsx
  pages/index.tsx
  prisma/schema.prisma
Labels: Database, Students

#86 Takshak
  .gitignore
  components/Forms/PersonalDetail.tsx
  package.json
  pages/api/auth/[...nextauth].ts
  pages/api/signup.ts
  pages/details.tsx
  pages/index.tsx
  pages/login.tsx
  pages/signout.tsx
  pages/signup.tsx
  prisma/schema.prisma
  yarn.lock
Labels: dashboard, Students

#88 Takshak
  components/Cards/Card.tsx
  components/Header.tsx
  components/Layouts/StudentsLayout.tsx
  components/Sidebar/StudentSidebar.tsx
  components/Sidebar/TGsidebar.tsx
  styles/Home.module.css
Labels: dashboard

#90 minor feat + Fix
  components/AttendanceColor.tsx
  components/Cards/Card.tsx
  components/Header.tsx
  components/Layouts/StudentsLayout.tsx
  components/Layouts/TgsLayout.tsx
  components/Sidebar/StudentSidebar.tsx
  components/Sidebar/TGsidebar.tsx
  components/Tables/AttendanceTable.tsx
  components/Tables/Table.tsx
  lib/checks.ts
  pages/api/tg/attendances.ts
  pages/api/tg/auth/[...nextauth].ts
  pages/index.tsx
  pages/tg/index.tsx
  pages/tg/login.tsx
  styles/Home.module.css
Labels: dashboard, TG Incharge, TG, Students, HOD

#91 fix : fixed some version 1 feature
  components/DataForms/FamilyDetail.tsx
  components/DataForms/FriendsDetail.tsx
  components/DataForms/PersonalDetail.tsx
  lib/xlSchema.ts
Labels: dashboard, enhancement, TG Incharge, HOD

#92 Takshak
  .dockerignore
  Dockerfile
  components/DataForms/FamilyDetail.tsx
  components/DataForms/FriendsDetail.tsx
  components/DataForms/PersonalDetail.tsx
  components/FilterItems/NumericFilterItem.tsx
  components/FilterItems/StringFilterItem.tsx
  components/Layouts/HodsLayout.tsx
  components/Pagination.tsx
  components/Sidebar/HodsSidebar.tsx
  docker-compose.yml
  lib/checks.ts
  lib/xlSchema.ts
  package.json
  pages/api/hod/auth/[...nextauth].ts
  pages/api/hod/tgs/index.ts
  pages/api/incharge/auth/[...nextauth].ts
  pages/api/incharge/students/index.ts
  pages/api/incharge/students/search.ts
  pages/api/incharge/students/unallocateTg.ts
  pages/api/incharge/students/updateTg.ts
  pages/api/signup.ts
  pages/api/tg/students/index.ts
  pages/hod/analytics.tsx
  pages/hod/index.tsx
  pages/hod/login.tsx
  pages/hod/reports.tsx
  pages/hod/students/[slug].tsx
  pages/hod/students/index.tsx
  pages/hod/tgs/[slug].tsx
  pages/hod/tgs/index.tsx
  pages/hod/user.tsx
  pages/incharge/index.tsx
  pages/incharge/login.tsx
  pages/incharge/tgs/[slug].tsx
  pages/incharge/tgs/index.tsx
  pages/incharge/user.tsx
  pages/tg/students/[slug].tsx
  pages/tg/students/index.tsx
  prisma/schema.prisma
  yarn.lock
Labels: Database, dashboard

#93 Feat : College header on students dashboard.
  pages/index.tsx
  public/header.png
Labels: dashboard, Students

#95 Minor fixes
  Dockerfile
  components/Sidebar/StudentSidebar.tsx
  docker-compose.yml
  pages/goals.tsx
  pages/index.tsx
  pages/settings.tsx
  pages/tasks.tsx
  pages/user.tsx
Labels: Database, dashboard, TG, Students, HOD

#96 Dakhole
  components/login.tsx
  pages/login.tsx
Labels: dashboard, TG Incharge, TG, Students, HOD

#97 Takshak
  .env.example
  components/Layouts/HodsLayout.tsx
  components/Sidebar/HodsSidebar.tsx
  components/login.tsx
  pages/hod/index.tsx
  pages/login.tsx
Labels: Database, dashboard, enhancement
